name: Build Mod

on: [push, pull_request]

jobs:
  build:
    name: Windows Build
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Geode SDK
      uses: geode-sdk/setup-geode-sdk@main

    - name: Build Mod
      uses: geode-sdk/build-geode-mod@main
