name: Build Mod

on: [push, pull_request]

jobs:
  build:
    name: Windows Build
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build Mod File
      shell: powershell
      run: |
        curl -sL https://github.com -o geode.zip
        Expand-Archive geode.zip -DestinationPath .
        geode sdk install
        geode profile auto
        geode package build .
